import './components/MyHomePage.js';
import './components/MyAboutPage.js';
import './components/MyContactPage.js';
import './components/MyFetchTest.js';
import './components/MyPokemonDetails.js';
import './components/MyPokemonCry.js';
import './components/MyPokemonSprites.js';
import './components/MySearchPokemon.js';
import './components/Clock.js'
import './components/Timer.js'
import './components/Chart.js'
import './components/PageChart.js'