name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write      # Needed to deploy to GitHub Pages
      id-token: write   # Needed for authentication

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Or your desired Node.js version
          cache: 'npm'         # Cache node_modules for faster builds

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # Or your build command (e.g., npm run build:prod)

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3 # Use a version that correctly handles the 'path' input
        with:
          path: dist/       # Deploy the contents of the 'dist' directory.  Trailing slash!